### ISSUE TITLE
Even Simpler update method?

### ISSUE THREAD

**Issue by ultrox** [martinseanhunt/padgey-nation-frontend#1]
Hi Martin, you are absolutely awesome for figuring this out. I was reading through your post on medium, and trying to figure out why not use something like this

```
  update = (cache, payload) => {
    const key = `ItemList:${payload.data.deleteItem.id}`;
    cache.data.delete(key);
    this.props.refetch();
  };

```

Instead of blowing all the cache with ItemList, looping not needed. I just wonder am I missing something?

**Comment by martinseanhunt** [comment]
@ultrox Thanks so much for checking out the article, I'm beyond happy it appears to be helping people!

This is what can be kind of tricky to understand about how the caching and refetching is working in Apollo. 

Your code above does work to delete the item from the cache and cause a refetch, however it will only cause a refetch of the CURRENT page. 

since It doesn't invalidate the cached data for other pages, we run in to an issue where the other pages will end up with incorrect data if those pages were already stored in our cache. Check out this example: https://imgur.com/a/opjHkTz notice how items 1,2 and 3 end up appearing to be duplicated? That's because they're already in the cached data for the query of the second page. 

We have to delete the entire cached data for all pages in order to ensure that each page gets refetched when it is next requested. Unfortunately there's no simple and quick way to do that (that I'm aware of) which is why we end up having to iterate over the entire cache.

**Comment by ultrox** [comment]
@martinseanhunt like I said you are awesome, you saved me so so much time. This is one of those moment If there where donation page to buy I would donate, that much you saved me time. 

Of course now it make sense, I'll change my code to loop over like this:

```
export const deleteCache = prefix => cache => {
  const reg = new RegExp(`^${prefix}`)
  Object.keys(cache.data.data).forEach(key => 
    key.match(reg) && cache.data.delete(key)
  )
}

```

**Comment by martinseanhunt** [comment]
@ultrox Thanks so much for the kind words. It really does mean a great deal to me. 

I hope this isn't too much of a cheeky ask, but the best thing you could possibly do for me is "applaud" the article on Medium if you haven't already. 

Either way, I'm so glad I could help!
